include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    todo: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    prefer_const_constructors: ignore

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - prefer_const_constructors
